######################################################################
# Automatically generated by qmake (3.0) Sat May 9 18:38:38 2015
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += build-Qt-resources-Desktop_Qt_5_4_1_clang_64bit-Debug.pro
